### ISSUE TITLE
Updating AVC Version file

### ISSUE THREAD

**Issue by wile1411** [DBooots/ESLDBeacons#2]
The AVC file contains some issues with the unix/weird quote symbol “ being used, so it's not being checked:

Current first line of ESLDBeacons file:      "NAME”:”ESLD Jump Beacons“,
probably should be:      "NAME":"ESLD Jump Beacons",

KSP min version is set to 1.1.3 (release was updated to 1.2)

Also, last release was version 0.90 - version file is still 0.81

**Comment by DBooots** [comment]
Fixed in commit 46f2813b3304a825c303366e98d50d5f669f89d1.
